# Image Input/Output
# ----------------------------------------------------------------------------------------------
height : 256
width : 256
in_channels : 3
num_classes : 6


# Training
# ----------------------------------------------------------------------------------------------
# unet/mod-unet/dncnn/u2net/vnet/unet++
model_name : &model unet
batch_size : 10
epochs : 25
learning_rate : !!float 3e-4
val_plot_epoch : 30
augment : True
transfer_lr : False
gpu : !!str 4


# Dataset
# ----------------------------------------------------------------------------------------------
patch_size : 256 # height = width, anyone is suitable
dataset_dir : /home/mdsamiul/semantic-segmentation/data/Aerial_Image/
root_dir : &root /home/mdsamiul/semantic-segmentation/dubai_satellite_image_keras
train_size : 0.8
x_train_dir : train/img/
x_valid_dir : valid/img/
x_test_dir : test/img/
y_train_dir : train/mask/
y_valid_dir : valid/mask/
y_test_dir : test/mask/

# Logger/Callbacks
# ----------------------------------------------------------------------------------------------
csv : True
val_pred_plot : True
lr : True
tensorboard : True
early_stop : True
checkpoint : True

early_stopping_technique : False
patience : 500 # required for early_stopping, if accuracy does not change for 500 epochs, model will stop automatically

# Evaluation
# ----------------------------------------------------------------------------------------------
load_model_name : unet_epochs_3_20-Feb-22.hdf5
load_model_dir : None


single_image : True # if True, then only index x_test image will plot
index : 10 # by default -1 means random image else specific index image provide by user
